### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by SchahinRohani** [porsager/postgres-shift#1]
Hello Rasmus Porsager, 
first of all, thank you for your nice postgres implementation!
Now i am looking for a clean solution for migrations and migration versionings. So i found this repo of yours.

What is the state of this project so far? Can somehow help you with this?

best regards,
Schahin Rohani

**Comment by joakimbeng** [comment]
Still looking for a solution for database migrations? Please have a look at https://emigrate.dev which supports migrations written using both CommonJS and ES Modules. It can be run with NodeJS, Bun or Deno and have plugins for different databases like PostgreSQL (which uses the `postgres` package) among others.

**Comment by nicolasembleton** [comment]
I've been using the library in a vendored fashion (clone and modify) and added types, clean-ups and a few new features (ability to pass a schema if you have multiple migration domains within your app, a few other things). If that's of interest, happy to push it here or fork the project (if the project owner does not have time to support this library / helper, in the meantime anyways).

**Comment by porsager** [comment]
Hehe, well, it's mostly making the documentation I don't have time for, even thought it's minimal.. I'm still using it myself, so I'd be happy to take a look at a PR ☺️

**Comment by nicolasembleton** [comment]
> Hehe, well, it's mostly making the documentation I don't have time for, even thought it's minimal.. I'm still using it myself, so I'd be happy to take a look at a PR ☺️

Apologies. I just noticed the response. Will publish within a week or two. Happy to make a brief documentation as well. I'm using it on a relatively regular basis and it's been working perfectly for me after I made the few modifications.

**Comment by porsager** [comment]
No worries :) About types, it has to be external d.ts, I am not looking to convert the project to typescript.

**Comment by porsager** [comment]
Help always welcomed, but library is what I would call "done" :)
