### ISSUE TITLE
Allow file migrations, avoiding the creation of intermediate folders

### ISSUE THREAD

**Issue by jopicornell** [porsager/postgres-shift#4]
I love the simplicity and the idea of this plugin, but one thing I didn't like is the obligation to use folders and inside an index.(sql|js) file, which isn't a big deal, but seems like it would be much comfortable to do it like this:
```
|- migrations
|-- 00001_create.sql
|-- 00002_update.js
|-- 00003_delete.sql
```

Obviously, this should be retrocompatible with existing migrations. 

I've been experimenting with the code and it is an easy fix. When I have it done I'll open a PR in case it is welcome as a feature.

**Comment by porsager** [comment]
Yeah, that's perfectly valid :) Good idea.
